version: "3"

services:
  mongo:
    image: mongo:5.0.5 
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=secret
  fcc-exercise-tracker-ms:
    image: madjiebimaa/fcc-exercise-tracker-ms:v1
    ports:
      - 3000:3000
    environment:
      - MONGO_HOST=localhost
      - MONGO_PORT=27017
      - MONGO_USER=root
      - MONGO_PASSWORD=secret
      - DB_NAME=fcc-exercise-tracker-ms
      - USER_COLLECTION=users
      - EXERCISE_COLLECTION=exercises
      - TIMEOUT_CONTEXT=2
      - SERVER_ADDRESS=:3000
    depends_on:
      - mongo